freebsd_instance:
  image_family: freebsd-13-0-snap
  cpu: 8
  memory: 16

ffmpeg_task:
  timeout_in: 120m
  requirements_script:
    - pkg install -y ffmpeg aria2
  downloading_script:
    - "aria2c --check-certificate=false --file-allocation=none --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 --header 'Host: nl24.seedr.cc' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' --header 'Accept-Language: id,en-US;q=0.7,en;q=0.3' --referer 'https://www.seedr.cc/files/164786004' --header 'Upgrade-Insecure-Requests: 1' 'https://nl24.seedr.cc/ff_get/876433683/Joseon.Exorcist.S01E01.1080p.WEB-DL.H264.AAC-AppleTor.mp4?st=qTlguSa895jWrAdgGgwEZQ&e=1616684829' --out 'Joseon.Exorcist.S01E01.1080p.WEB-DL.H264.AAC-AppleTor.mp4'"
  rendering_script:
    - ffmpeg -i "Joseon.Exorcist.S01E01.1080p.WEB-DL.H264.AAC-AppleTor.mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="Joseon Exorcist Episode 1" -preset veryfast -pix_fmt yuv420p10le -s 1280x720 01.mkv
    - ls -hal
  binaries_artifacts:
    path: "01.mkv"
