container:
  image: "registry.gitlab.com/tigefa/ffmpeg"

ffmpeg_task:
  requirements_script:
    - apt update && apt install -y lshw neofetch
    - whoami
    - pwd
    - ls -hal
    - neofetch
    - lshw
