container:
  image: "registry.gitlab.com/tigefa/ffmpeg"

ffmpeg_task:
  requirements_script:
    - apt update && apt install -y lshw neofetch
    - dropbox start
    - sleep 30
    - curl -sSL https://wtfismyip.com/json
    - dropbox status
    - whoami
    - pwd
    - ls -hal
    - neofetch
    - lshw
    - dropbox status
