container:
  image: "registry.gitlab.com/tigefa/ffmpeg"

ffmpeg_task:
  requirements_script:
    - apt update && apt install -y lshw neofetch
    - dropbox start
    - wget https://www.dropbox.com/s/dl/v60fnh0h78u3ytj/aws.csv
    - aws configure import --csv file://aws.csv
    - sleep 30
    - curl -sSL https://wtfismyip.com/json
    - dropbox status
    - whoami
    - pwd
    - ls -hal
    - neofetch
    - lshw
    - dropbox status
