freebsd_instance:
  image_family: freebsd-13-0-snap
  cpu: 8
  memory: 16

ffmpeg_task:
  timeout_in: 120m
  requirements_script:
    - pkg install -y ffmpeg aria2
  downloading_script:
    - "aria2c --check-certificate=false --min-split-size=100M --max-concurrent-downloads=16 --max-connection-per-server=16 https://www.dropbox.com/s/dl/dho57ot0ade9nwy/Sisyphus.The.Myth.S01E11.1080p.NF.WEB-DL.DDP2.0.x264-Imagine.mkv"
  rendering_script:
    - ffmpeg -i "Sisyphus.The.Myth.S01E11.1080p.NF.WEB-DL.DDP2.0.x264-Imagine.mkv" -threads 16 -c:v libx265 -c:a copy -metadata title="Sisyphus The Myth Episode 11" -preset veryfast -pix_fmt yuv420p10le -s 1280x720 11.mkv
    - ls -hal
  binaries_artifacts:
    path: "11.mkv"
